// generated by tools/gen_ranks.py from docs/RANGI.txt - do not edit
#include "ui/ranks.h"

#include "ui/lang.h"

namespace cr {

// { English, Polish, Spanish, Latin } for levels 1-1 up (index = level - 1)
static const char *const kRanks[35][4] = {
    {"Speed Bump", "Prog Zwalniajacy", "Badén", "Gibbus Viae"},
    {"Road Snack", "Przekaska dla Tira", "Aperitivo de Camión", "Cibus Plaustri"},
    {"Professional Tree Hugger", "Zawodowy Przytulacz Drzew", "Abrazaárboles Profesional", "Amplexator Arborum"},
    {"Accidental Pedestrian", "Przypadkowy Przechodzien", "Peatón Accidental", "Pedes Fortuitus"},
    {"Almost Roadkill", "Prawie Rozjechany", "Casi Atropellado", "Paene Contritus"},
    {"Puddle Jumper", "Skoczek przez Kaluze", "Saltacharcos", "Saltator Lacunarum"},
    {"Log Surfer Trainee", "Stazysta na Klodzie", "Aprendiz de Surfista de Troncos", "Tiro Truncorum"},
    {"Crosswalk Rookie", "Swiezak na Pasach", "Novato del Paso de Cebra", "Tiro Transitus"},
    {"Bumper Dodger", "Unikacz Zderzakow", "Esquivaparachoques", "Vitator Plaustrorum"},
    {"Critter with a Plan", "Zwierzak z Planem", "Bicho con un Plan", "Bestiola cum Consilio"},
    {"Traffic Whisperer", "Zaklinacz Ruchu", "Susurrador del Tráfico", "Susurrator Viarum"},
    {"Lily Pad Captain", "Kapitan Lilii", "Capitán de los Nenúfares", "Centurio Nymphaearum"},
    {"Rail Dancer", "Tancerz na Torach", "Bailarín de las Vías", "Saltator Ferriviae"},
    {"Roadside Ninja", "Ninja z Pobocza", "Ninja de la Cuneta", "Ninja Marginis"},
    {"Crossing Veteran", "Weteran Przejsc", "Veterano de los Cruces", "Veteranus Transituum"},
    {"Asphalt Acrobat", "Akrobata Asfaltu", "Acróbata del Asfalto", "Petaurista Bituminis"},
    {"River Tamer", "Pogromca Rzeki", "Domador del Río", "Domitor Fluminis"},
    {"Train Teaser", "Ten, co Drazni Pociagi", "Provocador de Trenes", "Lacessitor Traminum"},
    {"Sergeant Snout", "Sierzant Ryjek", "Sargento Hocico", "Optio Rostrum"},
    {"Boss of the Street", "Szef Ulicy", "Jefe de la Calle", "Dominus Viae"},
    {"Highway Hero", "Bohater Autostrady", "Héroe de la Autopista", "Heros Viae Publicae"},
    {"Captain Crossroads", "Kapitan Skrzyzowanie", "Capitán Encrucijada", "Centurio Trivii"},
    {"Lord of the Logs", "Wladca Klod", "Señor de los Troncos", "Dominus Truncorum"},
    {"Major Mayhem", "Major Zamieszanie", "Comandante Caos", "Tribunus Tumultus"},
    {"Commander of Crossings", "Komendant Przejsc", "Comandante de los Cruces", "Legatus Transituum"},
    {"Iron Nerve", "Zelazne Nerwy", "Nervios de Acero", "Nervi Ferrei"},
    {"Storm on Legs", "Burza na Nozkach", "Tormenta con Patas", "Tempestas Pedestris"},
    {"General Gridlock", "General Korek", "General Atasco", "Imperator Obstructionis"},
    {"Drivers' Nightmare", "Postrach Kierowcow", "Pesadilla de los Conductores", "Terror Aurigarum"},
    {"Master of the Road", "Mistrz Drogi", "Maestro del Camino", "Magister Viae"},
    {"Legend of the Lane", "Legenda Pasa", "Leyenda del Carril", "Fabula Semitae"},
    {"Myth of the Motorway", "Mit Autostrady", "Mito de la Autopista", "Mythus Viae Regiae"},
    {"Golden Step", "Zloty Krok", "Paso de Oro", "Gradus Aureus"},
    {"Supreme Crosser", "Najwyzszy Przechodzien", "Cruzador Supremo", "Transitor Supremus"},
    {"The One Who Crossed", "Ten, Ktory Przeszedl", "El Que Cruzó", "Qui Transiit"},
};
static const char *const kTopRank[4] = {"Unkillable Legend", "Niesmiertelna Legenda", "Leyenda Inmortal", "Fabula Immortalis"};

int rankCount() { return 35; }

const char *rankName(int level)
{
    const int i = level - 1;
    return i < 0 ? kRanks[0][lang::current()] : i < 35 ? kRanks[i][lang::current()]
                                                                 : kTopRank[lang::current()];
}

} // namespace cr
