// Generated by tools/make_amiga_font.py - do not edit.
#ifndef BH_FONT_IDS_H
#define BH_FONT_IDS_H

#define BH_FONT_FACES 4
#define BH_FONT_12   0  /* line height 12 */
#define BH_FONT_14   1  /* line height 14 */
#define BH_FONT_18   2  /* line height 18 */
#define BH_FONT_32   3  /* line height 32 */

#endif
